- name: Demo Register
  hosts: all
  tasks:
   - name: Get Update
     ansible.builtin.shell: uptime
     register: SHELL_OUTPUT
     
   - name: Print Output
     ansible.builtin.debug:
     msg: "{{SHELL_OUTPUT}}"